### ISSUE TITLE
页面刷新子应用加载不了

### ISSUE THREAD

**Issue by CHENLiver** [FoneQinrf/qiankun-project#1]
![image](https://user-images.githubusercontent.com/13173587/90602549-87065900-e22c-11ea-8751-c96397980335.png)

**Comment by FoneQinrf** [comment]
是最新的代码？

**Comment by FoneQinrf** [comment]
我本地跑了下 刷新没问题

**Comment by CHENLiver** [comment]
是的 切换路由是没有问题的  刷新页面就会有问题

**Comment by FoneQinrf** [comment]
子应用是渲染在#app-qiankun这个节点里的 渲染的时候#app-qiankun这个节点没找到   这个问题一开始就发现了 最新的代码应该不会存在这个问题的  我自己跑了下也没问题

**Comment by CHENLiver** [comment]
大佬 master 是最新的代码吗，我试过了重新下载下来 运行 还是有这样的情况出现

**Comment by CHENLiver** [comment]
刷新几次就会出现了

**Comment by FoneQinrf** [comment]
startQiankun(apps)的加载 放到Layout下的nextTick生命周期去加载就没问题了

**Comment by CHENLiver** [comment]
好的 解决了 谢谢大佬

**Comment by FoneQinrf** [comment]
startQiankun(apps)的加载 放到Layout下的nextTick生命周期去加载就没问题了

**Comment by FoneQinrf** [comment]
startQiankun(apps)的加载 放到Layout下的nextTick生命周期去加载就没问题了
